# This is a basic workflow to help you get started with Actions

name: CI-test

on:
  push:
    branches: [ dev, main ]


jobs:

  Deploy:
    runs-on: ubuntu-latest

    steps:      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'github-actions-service-alan'
      
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy With rsync
        run: rsync -avz ./public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/nussati/githubaction-folder
  
  Build:
    runs-on: ubuntu-latest
    needs: Deploy
    steps:  
      - name: Running Composer and Yarn
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/nussati/githubaction-folder 
            cat robots.txt > meuteste.txt
